[build]
  # Build command for Railway deployment
  command = "npm run install:all && npm run build"
  
  # Publish directory - client build output
  publish = "client/dist"
  
  # Functions directory for serverless functions
  functions = "server"

[build.environment]
  # Environment variables for Railway
  NODE_ENV = "production"
  NPM_FLAGS = "--production"
  
[context.production]
  # Production-specific build settings
  command = "npm run install:all && npm run build"
  
[context.production.environment]
  # Production environment variables
  NODE_ENV = "production"
  
[dev]
  # Development environment
  command = "npm run dev"
  
[dev.environment]
  NODE_ENV = "development"

[functions]
  # Serverless functions configuration
  directory = "server"
  
[functions.environment]
  # Function-specific environment variables
  NODE_ENV = "production"
